	
package es1;

public interface Constants {

	
	int PLANET_NUMBER = 6;
	int DELTA_TIME = 1;
	double GRAVITY = 6.67408 * 10E-11;
	
	int MIN_DISTANCE_BETWEEN_PLANETS = 7;
	int MAX_MASS = 1000000000;
	int MAX_POSITION_X = 1300;
	int MAX_POSITION_Y = 700;
	//public static int MAX_SPEED = 1;
	
	//WINDOW SIZES
	int BUTTON_SPACING = 15;
	int PANEL_SIZE_X = 1300;
	int PANEL_SIZE_Y = 700;
	int PANEL_BORDER_SIZE_X = 120;
	int DRAWING_PANEL_SIZE_X = PANEL_SIZE_X - PANEL_BORDER_SIZE_X;
	int DRAWING_PANEL_SIZE_Y = PANEL_SIZE_Y;
	int BUTTON_SIZE_X = PANEL_BORDER_SIZE_X - BUTTON_SPACING * 2;
	int BUTTON_SIZE_Y = 40;

}
